
export const HOME_LINK = "/"
export const TUTORIALS_LINK = "/tutorials"
export const LITEPAPER_LINK = "/Polarfox Litepaper V2.10.pdf"
export const GITHUB_LINK = "https://github.com/Polarfox-DEX"
export const DEX_LINK = "https://dex.polarfox.io"
export const ANALYTICS_LINK = "https://analytics.polarfox.io"
export const MININGPOOL_LINK = "https://dex.polarfox.io/#/pfx"
export const BRIDGE_LINK = "https://bridge.polarfox.io"
export const AKITA_LINK = "https://akita.network"
export const ABOUT_LINK = "/about"
export const ROADMAP_LINK = "/#roadmap"
export const FAQ_LINK = "/faq"
export const METAMASK_LINK = "https://metamask.io/download"
export const CLAIM_LINK = "/claim"

